### ISSUE TITLE
Multiple games

### ISSUE THREAD

**Issue by LordSentox** [LordSentox/othello#9]
One player may want to play against multiple opponents at a time, so it should be possible to
have multiple games running, and not just one.

**Comment by Scosh** [comment]
If there is a fullscreen mode, how should/would multiple boards/windows be handled there?

**Comment by LordSentox** [comment]
It is possible to have multiple games now.

**Comment by LordSentox** [comment]
Closing this issue now. Please continue the discussion on how to handle multiple games in #14.
